# Generated by Django 5.1.6 on 2026-03-10 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_owner', 'Super Owner'), ('sub_agent', 'Sub Agent'), ('admin', 'Platform Admin'), ('org_admin', 'Org Admin'), ('user', 'User'), ('brand', 'Brand'), ('factory', 'Factory'), ('third_party', '3rd Party')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('client_success', 'Client Success'), ('qa_supervisor', 'QA Supervisor'), ('technical', 'Technical Support'), ('billing', 'Billing Support')], max_length=30)),
                ('client_ids', models.JSONField(blank=True, default=list, help_text='List of Organization UUIDs this agent can access')),
                ('allowed_actions', models.JSONField(blank=True, default=list, help_text='List of allowed actions: view_reports, add_users, handle_tickets, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'sub_agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'super_owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FounderActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('impersonate_start', 'Impersonate Start'), ('impersonate_end', 'Impersonate End'), ('suspend_user', 'Suspend User'), ('unsuspend_user', 'Unsuspend User'), ('suspend_client', 'Suspend Client'), ('unsuspend_client', 'Unsuspend Client'), ('create_agent', 'Create Agent'), ('revoke_agent', 'Revoke Agent'), ('update_agent', 'Update Agent'), ('console_login', 'Console Login'), ('config_change', 'Config Change')], max_length=30)),
                ('target_client_id', models.UUIDField(blank=True, null=True)),
                ('target_client_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('session_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_actions_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_fo_timesta_11c764_idx'), models.Index(fields=['actor', '-timestamp'], name='accounts_fo_actor_i_829ca6_idx'), models.Index(fields=['action'], name='accounts_fo_action_559094_idx')],
            },
        ),
    ]
