# Generated by Django 5.1.6 on 2026-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_report_file_to_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='product_category',
            field=models.CharField(choices=[('garments', 'Garments'), ('gloves', 'Gloves'), ('footwear', 'Footwear'), ('headwear', 'Headwear'), ('accessories', 'Accessories'), ('bags', 'Bags')], default='garments', max_length=20),
        ),
    ]
