# Generated by Django 5.1.6 on 2026-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_demolead_add_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='audit_compliance',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AddField(
            model_name='factory',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factory',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factory',
            name='infrastructure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='production_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='total_manpower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=20),
        ),
    ]
