# Generated by Django 5.1.6 on 2026-03-08 12:29

import django.db.models.deletion
from django.db import migrations, models


def migrate_inspection_status(apps, schema_editor):
    """Set status based on existing result values, and rename conditional → conditional_pass."""
    Inspection = apps.get_model('core', 'Inspection')
    # Inspections with a definitive result have been reviewed/approved
    Inspection.objects.filter(result__in=['pass', 'fail']).update(status='approved')
    # Rename conditional → conditional_pass and mark as approved
    Inspection.objects.filter(result='conditional').update(status='approved', result='conditional_pass')
    # Pending = still draft
    Inspection.objects.filter(result='pending').update(status='draft')
    # N/A = cancelled
    Inspection.objects.filter(result='na').update(status='cancelled', result='pending')
    # Also fix overall_result
    Inspection.objects.filter(overall_result='conditional').update(overall_result='conditional_pass')
    Inspection.objects.filter(overall_result='na').update(overall_result=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_factory_audit_compliance_factory_certifications_and_more'),
        ('templates_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='template_id',
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('report_pending', 'Report Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='templates_engine.inspectiontemplate'),
        ),
        migrations.RunPython(migrate_inspection_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inspection',
            name='overall_result',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional_pass', 'Conditional Pass')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='result',
            field=models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional_pass', 'Conditional Pass')], default='pending', max_length=20),
        ),
    ]
