# Generated by Django 5.1.6 on 2026-02-26 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='aql_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='email_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_no',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='overall_result',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass'), ('na', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='signature_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inspection',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='template_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='master_order',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='order_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('pre_production', 'Pre-Production'), ('inline', 'Inline'), ('final', 'Final'), ('lab_test', 'Lab Test'), ('fri', 'FRI'), ('dupro', 'Dupro'), ('pre_final', 'Pre-Final')], default='inline', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='result',
            field=models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass'), ('na', 'N/A')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('on_track', 'On Track'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionDefect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('defect_code', models.CharField(max_length=20)),
                ('defect_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('other', 'Other')], default='minor', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='core.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending'), ('na', 'N/A')], max_length=20, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.inspection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(default='checklist', max_length=50)),
                ('spec_value', models.CharField(blank=True, max_length=255)),
                ('tolerance', models.CharField(blank=True, max_length=100)),
                ('actual_value', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending'), ('na', 'N/A')], max_length=20, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('comment', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.inspectionsection')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='viewer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='core.productionorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('order', 'user')},
            },
        ),
    ]
