# Generated by Django 5.1.6 on 2026-03-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inspection_aql_level_inspection_email_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demolead',
            name='factories_count',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='demolead',
            name='monthly_inspections',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demolead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted')], default='new', max_length=20),
        ),
    ]
