# Generated by Django 5.1.6 on 2026-03-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demolead_factories_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab-reports/'),
        ),
    ]
