# Generated by Django 5.1.6 on 2026-03-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productionorder_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='demolead',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
