# Generated by Django 5.1.6 on 2026-03-08 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_user_notification_preferences'),
        ('core', '0007_factory_audit_compliance_factory_certifications_and_more'),
        ('workflow', '0002_alter_workflowstage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('phase', models.CharField(choices=[('product_development', 'Product Development'), ('order_management', 'Order Management'), ('production_prep', 'Production Preparation'), ('production_execution', 'Production Execution'), ('quality_control', 'Quality Control'), ('logistics', 'Logistics'), ('combined_operational', 'Combined Operational'), ('quality_system', 'Quality System')], max_length=30)),
                ('phase_sequence', models.IntegerField(default=0)),
                ('product_category', models.CharField(blank=True, choices=[('garments', 'Garments'), ('gloves', 'Gloves'), ('footwear', 'Footwear'), ('headwear', 'Headwear'), ('accessories', 'Accessories'), ('bags', 'Bags')], default='', max_length=20)),
                ('submitted_by_role', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_by_role', models.CharField(blank=True, default='', max_length=100)),
                ('approved_by_role', models.CharField(blank=True, default='', max_length=100)),
                ('next_template_code', models.CharField(blank=True, default='', max_length=10)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates', to='workflow.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['phase_sequence'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TemplateRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revision_count', models.IntegerField(default=0)),
                ('handover_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_records', to='core.productionorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_records', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_records', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='templates_engine.inspectiontemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('header', 'Header'), ('context', 'Product/Order Context'), ('tasks', 'Department Tasks'), ('data', 'Technical Data'), ('attachments', 'Attachments/Evidence'), ('output', 'Department Output'), ('approval', 'Approval & Handover')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='templates_engine.inspectiontemplate')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('template', 'block_type')},
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('field_key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('checkbox', 'Checkbox'), ('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('file', 'File Upload'), ('textarea', 'Text Area'), ('signature', 'Signature'), ('table', 'Table')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list)),
                ('default_value', models.CharField(blank=True, default='', max_length=500)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('auto_fill_source', models.CharField(blank=True, default='', max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates_engine.templatesection')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('section', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='template-values/%Y/%m/')),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='templates_engine.templatefield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='templates_engine.templaterecord')),
            ],
            options={
                'unique_together': {('record', 'field')},
            },
        ),
    ]
