# Generated by Django 5.1.6 on 2026-03-06 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstage',
            options={'ordering': ['sequence_number', 'sort_order']},
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='delay_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='on_fail_go_to_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='stage_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='output_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='product_category',
            field=models.CharField(blank=True, choices=[('garments', 'Garments'), ('gloves', 'Gloves'), ('footwear', 'Footwear'), ('headwear', 'Headwear'), ('accessories', 'Accessories'), ('bags', 'Bags')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='stages_json',
            field=models.JSONField(default=list, help_text='Legacy field — use template_stages relation instead'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stages', to='workflow.department'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplateStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=150)),
                ('stage_code', models.CharField(max_length=50)),
                ('sequence_number', models.IntegerField()),
                ('approver_role', models.CharField(blank=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('typical_duration_days', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('on_fail_go_to_seq', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_stages', to='workflow.department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_stages', to='workflow.workflowtemplate')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('template', 'sequence_number')},
            },
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='template_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workflow.workflowtemplatestage'),
        ),
    ]
