# Generated by Django 5.1.6 on 2026-03-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_trial_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
