# Generated by Django 5.1.6 on 2026-03-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_is_trial_locked_organization_trial_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Platform Admin'), ('org_admin', 'Org Admin'), ('user', 'User'), ('brand', 'Brand'), ('factory', 'Factory'), ('third_party', '3rd Party')], default='user', max_length=20),
        ),
    ]
