# Generated by Django 5.1.6 on 2026-03-09 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_user_notification_preferences'),
        ('core', '0008_inspection_status_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dms/%Y/%m/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(blank=True, choices=[('design', 'Design'), ('sampling', 'Sampling'), ('costing', 'Costing'), ('production', 'Production'), ('quality', 'Quality'), ('packing', 'Packing'), ('lab_testing', 'Lab Testing'), ('logistics', 'Logistics')], max_length=50)),
                ('doc_category', models.CharField(blank=True, choices=[('tech_pack', 'Tech Pack'), ('lab_report', 'Lab Report'), ('shipping_doc', 'Shipping Document'), ('invoice', 'Invoice'), ('certificate', 'Certificate'), ('inspection_report', 'Inspection Report'), ('sample_photo', 'Sample Photo'), ('packing_list', 'Packing List'), ('defect_photo', 'Defect Photo'), ('audit_report', 'Audit Report'), ('sop', 'SOP'), ('other', 'Other')], default='other', max_length=50)),
                ('visibility', models.CharField(choices=[('private', 'Only Uploader'), ('team', 'Same Organization'), ('brand', 'Brand Can See'), ('shared', 'Via Link')], default='team', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_documents', to='core.factory')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_documents', to='core.productionorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_documents', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'Uploaded'), ('view', 'Viewed'), ('download', 'Downloaded'), ('delete', 'Deleted')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.manageddocument')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='manageddocument',
            index=models.Index(fields=['organization', 'is_deleted'], name='documents_m_organiz_90a6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='manageddocument',
            index=models.Index(fields=['order', 'is_deleted'], name='documents_m_order_i_4465bc_idx'),
        ),
        migrations.AddIndex(
            model_name='manageddocument',
            index=models.Index(fields=['factory', 'is_deleted'], name='documents_m_factory_fe3312_idx'),
        ),
        migrations.AddIndex(
            model_name='manageddocument',
            index=models.Index(fields=['department'], name='documents_m_departm_af468b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document', 'timestamp'], name='documents_d_documen_bfc53a_idx'),
        ),
    ]
