# Generated by Django 5.1.6 on 2026-03-09 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccesslog',
            name='action',
            field=models.CharField(choices=[('upload', 'Uploaded'), ('view', 'Viewed'), ('download', 'Downloaded'), ('delete', 'Deleted'), ('share_created', 'Share Link Created'), ('share_accessed', 'Accessed via Share Link')], max_length=20),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('access_count', models.IntegerField(default=0)),
                ('max_access', models.IntegerField(default=10)),
                ('requires_watermark', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='documents.manageddocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='documents_s_token_0d08c0_idx'), models.Index(fields=['document', 'is_revoked'], name='documents_s_documen_75f550_idx')],
            },
        ),
    ]
