# Generated by Django 5.1.6 on 2026-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentaccesslog_action_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccesslog',
            name='action',
            field=models.CharField(choices=[('upload', 'Uploaded'), ('view', 'Viewed'), ('download', 'Downloaded'), ('delete', 'Deleted'), ('share_created', 'Share Link Created'), ('share_accessed', 'Accessed via Share Link'), ('export_pdf', 'Exported as PDF'), ('email_share', 'Shared via Email'), ('save_draft', 'Saved as Draft')], max_length=20),
        ),
    ]
