# Generated by Django 5.1.6 on 2026-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('general', 'General'), ('submission_note', 'Submission Note'), ('approval_note', 'Approval Note'), ('rejection_reason', 'Rejection Reason'), ('challenge', 'Challenge'), ('feedback', 'Feedback'), ('delay_reason', 'Delay Reason')], default='general', max_length=30),
        ),
    ]
